language: node_js
dist: trusty
sudo: required
install:
- npm install
jobs:
  include:
    - stage: "Build"
      script:
        - npm run lint    || travis_terminate 1;
        - npm run build   || travis_terminate 1;
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run test || travis_terminate 1;
    - script: npm run test:e2e || travis_terminate 1;
      name: "E2E Tests"
notifications:
  email:
    recipients:
    - guyso@wix.com
